language: cpp
dist: xenial
compiler: gcc

install: 
  - sudo apt-get install -qq qt5-qmake qt5-default

script: 
  - cd Code
  - qmake -qt=qt5
  - make release
  - time ./eed 
  - gprof djog_unos_2018 > gprof.log
  - head gprof.log -n 500
